# name: page

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: macOS-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.5
#         with:
#           node-version: "12"

#       - name: Cache node modules
#         uses: actions/cache@v2
#         env:
#           cache-name: cache-node-modules
#         with:
#           path: ./node_modules
#           key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package.json') }}
#           restore-keys: |
#             cache-node-modules-

#       - name: Run ci
#         run: |
#           npm install
#           npm run ci

# 项目名
name: decrystal

# 只有在master分支发生push事件时触发
on:
  push:
    branches:
      - main

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout
        uses: actions/checkout@main

      # 下载node，我这里指定了15.x，这个版本可随意，高于dumi规定的node版本即可
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.2

      # 打包代码
      - name: Build Project
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run docs:build

      # 部署到github
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: build # 打包的内容放到build分支下
          folder: docs-dist
